#Pset - 7
user_input = input(" Enter the some input: ")
a = user_input.upper()
b = a.replace("A" ,"4")
c = b.replace("B", "I3")
d = c.replace('E', '3')
e = d.replace('I', '1')
f = e.replace('H', '#')
g = f.replace("M", "[/\/\]")
h = g.replace('O', '0')
i = h.replace('S', '5')
j = i.replace('T', '5')
k = j.replace('U', '[(_)]')
print(k)
